---
title: "dashboard"
author: "shichi"
date: "`r Sys.time()`"
output: 
  flexdashboard::flex_dashboard:
    orientation: "row"
    theme: flatly

---

```{r setup, include=FALSE}
library(flexdashboard)
library(ggplot2)
library(data.table)
library(formattable)
library(tidyr)
library(plotly)
output.dt <- fread("data.csv", encoding = "UTF-8")
```


row {data-height=25%}
----

### card1 {data-width=35%}

```{r}
asset_fresh <- output.dt$asset %>% .[length(.)]
valueBox(asset_fresh, 
         caption = "Total Asset",
         icon = "glyphicon glyphicon-yen",
         color = ifelse(asset_fresh < 2000000, "warning", "success")
         )
```

### card2 {data-width=35%}

```{r}
stock_fresh <- output.dt$amount[output.dt$details == "Stock"] %>% sum()
valueBox(stock_fresh, 
         caption = "Total Stock",
         icon = "glyphicon glyphicon-tint",
         color = ifelse(stock_fresh > 1000000, "warning", "success")
         )
```

### card3 {data-width=30%}

```{r}
tax_fresh <- fread("data.csv", encoding = "UTF-8")
tax_fresh <- tax_fresh[tax_fresh$`I/O` == "日経" | tax_fresh$`I/O` == "朝日" | tax_fresh$`I/O` == "臨時", ]
tax_fresh <- tax_fresh[as.character(substr(Sys.Date(),1,4)) == as.character(substr(tax_fresh$ds,1,4)),]  %>% 
  select(amount) %>% 
  sum()
tax_fresh <- 1030000 - tax_fresh

valueBox(tax_fresh, 
         caption = "Tax limit",
         icon = "glyphicon glyphicon-flag",
         color = ifelse(tax_fresh < 100000, "red", "success")
         )
```

column {data-height=50%}
----

### Assets  {data-width=70%}

```{r}
asset.dt <- output.dt %>% 
  select(ds, amount, details) %>% 
  data.table(. , tmp = paste0(.$ds ,.$details)) %>% 
  group_by(tmp) %>% 
  summarise(total = sum(amount))

asset.dt <-  asset.dt %>% 
  data.table(ds = as.Date(substr(.$tmp, 1, 10)), amount = .$total, details = substr(.$tmp, 11, 20)) %>% 
  dcast(ds ~ details, value.var = "amount") %>% 
  data.frame()
asset.dt[is.na(asset.dt)] <- 0


for(i in 1:nrow(asset.dt)){
  for(j in 2:ncol(asset.dt))
    if(i != 1){
      asset.dt[i,j] <- asset.dt[i-1,j] + asset.dt[i,j]
    }
}
for(i in 1:nrow(asset.dt)){
  for(j in 3:ncol(asset.dt)){
    asset.dt[i,j] <- asset.dt[i,j-1] + asset.dt[i,j]
  }
}

p <- plot_ly(asset.dt, x = ~ds, y = ~Yucho, name = 'Yucho', type = 'scatter', mode = 'none', fill = 'tozeroy', fillcolor = '#97D1C7', showlegend = FALSE) %>%
  add_trace(y = ~Stock, name = 'Stock', fillcolor = '#F58A88') %>%
  add_trace(y = ~Mizuho, name = 'Mizuho', fillcolor = '#73ABC2') %>%
  layout(xaxis = list(showgrid = TRUE),
         yaxis = list(title = "Total Assets",
                      showgrid = TRUE))

p


```

### Pie  {data-width=30%}

```{r}
asset.dt <- output.dt %>% 
  select(ds, amount, details) %>% 
  data.table(. , tmp = paste0(.$ds ,.$details)) %>% 
  group_by(tmp) %>% 
  summarise(total = sum(amount))

asset.dt <-  asset.dt %>% 
  data.table(ds = as.Date(substr(.$tmp, 1, 10)), amount = .$total, details = substr(.$tmp, 11, 20)) %>% 
  dcast(ds ~ details, value.var = "amount") %>% 
  data.frame()
asset.dt[is.na(asset.dt)] <- 0


for(i in 1:nrow(asset.dt)){
  for(j in 2:ncol(asset.dt))
    if(i != 1){
      asset.dt[i,j] <- asset.dt[i-1,j] + asset.dt[i,j]
    }
}
for(i in 1:nrow(asset.dt)){
  for(j in 3:ncol(asset.dt)){
    asset.dt[i,j] <- asset.dt[i,j-1] + asset.dt[i,j]
  }
}
asset.dt[,2:4] <- asset.dt[,2:4]/apply(asset.dt[,2:4],1,sum)
for(i in 1:nrow(asset.dt)){
  for(j in 3:ncol(asset.dt)){
    asset.dt[i,j] <- asset.dt[i,j-1] + asset.dt[i,j]
  }
}


p <- plot_ly(asset.dt, x = ~ds, y = ~Yucho, name = 'Yucho', type = 'scatter', mode = 'none', fill = 'tozeroy', fillcolor = '#97D1C7', showlegend = FALSE) %>%
  add_trace(y = ~Stock, name = 'Stock', fillcolor = '#F58A88') %>%
  add_trace(y = ~Mizuho, name = 'Mizuho', fillcolor = '#73ABC2') %>%
  layout(xaxis = list(showgrid = TRUE),
         yaxis = list(title = "Total Assets",
                      showgrid = TRUE))

p
```


column {data-height=35%}
----

### Details {data-width=35%}

```{r}

asset.dt <- output.dt %>% 
  select(ds, amount, details) %>% 
  data.table(. , tmp = paste0(.$ds ,.$details)) %>% 
  group_by(tmp) %>% 
  summarise(total = sum(amount))

asset.dt <-  asset.dt %>% 
  data.table(ds = as.Date(substr(.$tmp, 1, 10)), amount = .$total, details = substr(.$tmp, 11, 20)) %>% 
  dcast(ds ~ details, value.var = "amount") %>% 
  data.frame()
asset.dt[is.na(asset.dt)] <- 0


for(i in 1:nrow(asset.dt)){
  for(j in 2:ncol(asset.dt))
    if(i != 1){
      asset.dt[i,j] <- asset.dt[i-1,j] + asset.dt[i,j]
    }
}

asset.dt <- data.table(asset.dt, Total = asset.dt$Mizuho+asset.dt$Stock+asset.dt$Yucho)

formattable(asset.dt, list(
  Total = color_bar("pink")
))

```



### Details {data-width=35%}

```{r}


formattable(output.dt, list(
  asset = color_bar("pink"),
  amount = formatter("span",
                      style = x ~ ifelse(x < 0 , formattable::style(color = "red"), formattable::style(color = "green")))

))

```

### Month {data-width=30%}

```{r}

outcome.dt <- output.dt %>% filter(amount < 0) %>% select(ds,amount)
outcome.dt <- outcome.dt[as.character(substr(Sys.Date(),1,4)) == as.character(substr(outcome.dt$ds,1,4)),]
outcome.dt$ds <- substr(outcome.dt$ds,6,7)
outcome.dt <- outcome.dt %>% group_by(ds) %>% summarise(total = sum(amount))

income.dt <- output.dt %>% filter(amount >= 0) %>% select(ds,amount)
income.dt <- income.dt[as.character(substr(Sys.Date(),1,4)) == as.character(substr(income.dt$ds,1,4)),]
income.dt$ds <- substr(income.dt$ds,6,7)
income.dt <- income.dt %>% group_by(ds) %>% summarise(total = sum(amount))

i_o.dt <- data.table(income = income.dt, outcome = -outcome.dt$total, diff = income.dt$total+outcome.dt$total)
colnames(i_o.dt) <- c("ds","income","outcome","diff")

formattable(i_o.dt, list(
  income = color_bar("pink"),
  outcome = color_bar("pink"),
  diff = formatter("span",
                      style = x ~ ifelse(x < 0 , formattable::style(color = "red"), formattable::style(color = "green")))

))
```

